
// src/config/constants.ts

export const opportunityCategories = [
    'All',
    'Environment',
    'Education',
    'Healthcare',
    'Animals',
    'Community Development',
    'Events',
    'Hunger Relief',
    'Arts & Culture',
    'Technology',
    'Seniors',
    'Youth',
    'Other',
];

export const commonSkills: string[] = [
    "Communication",
    "Teamwork",
    "Problem Solving",
    "Leadership",
    "Organization",
    "Event Planning",
    "Fundraising",
    "Teaching",
    "Mentoring",
    "Graphic Design",
    "Web Development",
    "Social Media Management",
    "Writing",
    "Editing",
    "Data Entry",
    "Manual Labor",
    "Cooking/Baking",
    "Driving",
    "First Aid",
    "Tutoring",
    "Gardening",
    "Crafting",
    "Public Speaking",
    "Research",
    "Customer Service",
];

export const commonCauses: string[] = [
    "Animal Welfare",
    "Arts & Culture",
    "Children & Youth",
    "Community Development",
    "Disaster Relief",
    "Education & Literacy",
    "Elderly Care",
    "Environment & Conservation",
    "Health & Wellness",
    "Housing & Homelessness",
    "Human Rights",
    "Hunger & Food Security",
    "International Aid",
    "Poverty Alleviation",
    "Refugee Support",
    "Social Justice",
    "Sports & Recreation",
    "Technology & Innovation",
    "Women's Issues",
];
